Removed Event class, was not being used.
CSESoftwareInc/Core pull request #2
Opened 2020-05-07 14:11 UTC by NickBehrends

Removed the event logic properties, was a hold over from pre-cqrs time.

2020-05-07 14:16 UTC, jared-craig-cse approved these changes

2020-05-07 14:27 UTC, TieDyeGeek approved these changes

2020-05-07 14:29 UTC, TieDyeGeek requested changes
Please update version number.

2020-06-12 21:55 UTC, TieDyeGeek commented
@NickBehrends - Please update this PR with an updated version number on the package.

2020-06-29 14:55 UTC, closed without merging